stages:
  - test
  - tag

test:
  stage: test
  script:
    - flutter test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

create_tag:
  stage: tag
  script:
    - chmod +x create_tag.sh
    - ./create_tag.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - when: manual             