name: qr_overlay
description: "custom animated qr scanner, based on mobile_scanner"
homepage: "https://gitlab.mdigital.kg/ch.yakshybaev/qr_scanner"

version: 1.0.0+1

environment:
  sdk: ^3.7.3

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^7.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true