name: qr_overlay
description: "custom animated qr scanner, based on mobile_scanner"
homepage: "https://github.com/mdigitalmobileteam-web/qr_overlay"
repository: "https://github.com/mdigitalmobileteam-web/qr_overlay"

version: 1.0.0

environment:
  sdk: ^3.7.3

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^7.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

scripts:
  create-tag:
    exec: ./create_tag.sh